{
  imports = [
    ./user.nix
    ./env.nix
    ./adb.nix
    ./defaultBrowser.nix
	./drivers.nix
	./greetd.nix
    ./audio.nix
    ./wine.nix
    ./nix-ld.nix
    ./cleanup.nix
    ./bluetooth.nix
    ./boot.nix
    ./security.nix
    ./v4l2.nix
    ./coding.nix
    ./reversing.nix
    ./network.nix
    ./trim.nix
  ];
}
